<?php $welcomeMessage = $block->getWelcome();?>
<?php echo $block->escapeHtml($block->getEmbed()); ?>
<?php echo $block->escapeHtml($block->getConversion()); ?>
<?php
switch ($block->getShowPart()) :
    case 'welcome':
    ?><li class="greet welcome" data-bind="scope: 'customer'">
            <!-- ko if: customer().fullname  -->
            <span data-bind="text: new String(
                    '<?php echo $block->escapeHtml(__('Welcome, %1!', '%1'));?>'
                ).replace('%1', customer().firstname)">
            </span>
            <!-- /ko -->
            <!-- ko ifnot: customer().fullname  -->
            <span data-bind="html:'<?php echo $block->escapeHtml($welcomeMessage) ?>'"></span>
            <!-- /ko -->
        </li>
        <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "customer": {
                            "component": "Magento_Customer/js/view/customer"
                        }
                    }
                }
            }
        }
        </script> 
    <?php
        break;
    case 'other':
        echo $block->getChildHtml();
        break;
        ?>
<?php endswitch; ?>